import { EVENT_TYPE_LABELS, type EventType } from "../lib/event-types";
import { formatEventDateTime } from "../lib/format-datetime";
import type { ReportData } from "../lib/reports-api";

type ReportDocumentProps = {
  data: ReportData;
  generatedByName?: string;
  createdAt?: string;
};

function formatMoney(value: string): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(Number(value));
}

function Metric({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="report-metric">
      <dt className="text-sm text-label">{label}</dt>
      <dd className="mt-0.5 text-lg font-light text-foreground">{value}</dd>
    </div>
  );
}

export function ReportDocument({
  data,
  generatedByName,
  createdAt,
}: ReportDocumentProps) {
  const feedbackRating =
    data.feedback.average_rating !== null
      ? `${data.feedback.average_rating.toFixed(1)} / 5`
      : "N/A";

  return (
    <article className="report-document mx-auto max-w-4xl">
      <header className="report-header border-b border-gray-200 pb-6 text-center">
        <p className="text-xs font-medium uppercase tracking-[0.2em] text-label">
          NSA Connect
        </p>
        <h1 className="mt-2 text-3xl font-light tracking-headline text-foreground">
          {data.title}
        </h1>
        <p className="mt-2 text-sm text-label">{data.period_label}</p>
        {generatedByName || createdAt ? (
          <p className="mt-3 text-xs text-label">
            {generatedByName ? `Generated by ${generatedByName}` : null}
            {generatedByName && createdAt ? " · " : null}
            {createdAt ? formatEventDateTime(createdAt) : null}
          </p>
        ) : null}
      </header>

      <section className="report-section mt-8">
        <h2 className="report-section-title">Events</h2>
        <dl className="mt-4 grid gap-4 sm:grid-cols-2">
          <Metric label="Total events held" value={data.events.total_events} />
        </dl>
        {data.events.events.length > 0 ? (
          <div className="report-table-wrap mt-4 overflow-x-auto">
            <table className="report-table min-w-full text-sm">
              <thead>
                <tr className="border-b border-gray-200 text-left text-label">
                  <th className="py-2 pr-4 font-medium">Event</th>
                  <th className="py-2 pr-4 font-medium">Date</th>
                  <th className="py-2 pr-4 font-medium">Category</th>
                  <th className="py-2 pr-4 font-medium">Attended</th>
                  <th className="py-2 font-medium">RSVP summary</th>
                </tr>
              </thead>
              <tbody>
                {data.events.events.map((event) => (
                  <tr key={event.id} className="border-b border-gray-100">
                    <td className="py-2 pr-4 text-foreground">{event.name}</td>
                    <td className="py-2 pr-4 text-label">
                      {formatEventDateTime(event.starts_at)}
                    </td>
                    <td className="py-2 pr-4 text-label">
                      {EVENT_TYPE_LABELS[event.event_type as EventType] ??
                        event.event_type}
                    </td>
                    <td className="py-2 pr-4 text-foreground">
                      {event.attendance_count}
                    </td>
                    <td className="py-2 text-label">
                      {event.rsvp_going_attended} attended /{" "}
                      {event.rsvp_going_no_show} no-show / {event.walk_ins}{" "}
                      walk-ins
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <p className="mt-3 text-sm text-label">No events in this period.</p>
        )}
      </section>

      <section className="report-section mt-8">
        <h2 className="report-section-title">Attendance</h2>
        <dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <Metric label="Total check-ins" value={data.attendance.total_checkins} />
          <Metric
            label="Member check-ins"
            value={data.attendance.total_member_checkins}
          />
          <Metric
            label="Guest check-ins"
            value={data.attendance.total_guest_checkins}
          />
          <Metric
            label="Events with check-ins"
            value={data.attendance.events_with_checkins}
          />
        </dl>
      </section>

      <section className="report-section mt-8">
        <h2 className="report-section-title">Finance</h2>
        <dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <Metric label="Total income" value={formatMoney(data.finance.total_income)} />
          <Metric
            label="Total expenses"
            value={formatMoney(data.finance.total_expense)}
          />
          <Metric label="Net balance" value={formatMoney(data.finance.net_balance)} />
          <Metric label="Entries logged" value={data.finance.entry_count} />
        </dl>
      </section>

      <section className="report-section mt-8">
        <h2 className="report-section-title">Dues</h2>
        {data.dues.semesters.length > 0 ? (
          <p className="mt-2 text-sm text-label">
            Semesters: {data.dues.semesters.join(", ")}
          </p>
        ) : null}
        <dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <Metric
            label="Total expected"
            value={formatMoney(data.dues.total_expected)}
          />
          <Metric
            label="Total collected"
            value={formatMoney(data.dues.total_collected)}
          />
          <Metric
            label="Total outstanding"
            value={formatMoney(data.dues.total_outstanding)}
          />
          <Metric label="Paid members" value={data.dues.paid_count} />
          <Metric label="Unpaid members" value={data.dues.unpaid_count} />
          <Metric label="Partial payments" value={data.dues.partial_count} />
        </dl>
      </section>

      <section className="report-section mt-8">
        <h2 className="report-section-title">Feedback</h2>
        <p className="mt-2 text-sm text-label">
          Aggregate ratings only — individual comments remain board-only.
        </p>
        <dl className="mt-4 grid gap-4 sm:grid-cols-3">
          <Metric label="Average rating" value={feedbackRating} />
          <Metric label="Total responses" value={data.feedback.response_count} />
          <Metric
            label="Events with feedback"
            value={data.feedback.events_with_feedback}
          />
        </dl>
      </section>

      <section className="report-section mt-8 pb-8">
        <h2 className="report-section-title">Membership</h2>
        <dl className="mt-4 grid gap-4 sm:grid-cols-3">
          <Metric
            label="Total approved members"
            value={data.membership.total_approved}
          />
          <Metric label="Board+ members" value={data.membership.board_plus_count} />
          <Metric label="General members" value={data.membership.general_count} />
        </dl>
      </section>
    </article>
  );
}
