export {
  colors,
  spacing,
  spacingScale,
  radii,
  shadows,
  motion,
  typography,
  layout,
} from "./tokens";
export type {
  ColorTokens,
  SpacingToken,
  RadiusToken,
  TypographySize,
} from "./tokens";

export { typeClass, fontFamilySans } from "./typography";
export type { TypeClassKey } from "./typography";

export { spaceClass, spacePx } from "./spacing";
export { cx } from "./cx";

/** CampusOS component library (canonical). Existing `components/ui/*` left intact. */
export {
  Button,
  Card,
  Input,
  Textarea,
  Select,
  Badge,
  Avatar,
  Divider,
  Skeleton,
  Spinner,
  fieldControlClassName,
  Sidebar,
  SidebarItem,
  SidebarSubItem,
  SidebarSection,
  TopHeader,
  SearchBar,
  NotificationMenu,
  ProfileMenu,
  Breadcrumb,
  useDismissibleMenu,
  HeroBanner,
  HeroBannerAction,
  StatCard,
  AnnouncementCard,
  ActivityCard,
  TaskCard,
  EventCard,
  QuickActionCard,
  ProfileCard,
  DataStatus,
  DataTableSkeleton,
  EmptyState,
  DataTable,
  Timeline,
  CalendarCard,
  ChartContainer,
  MetricCard,
  Alert,
  Toast,
  ToastViewport,
  Modal,
  ConfirmationDialog,
  Drawer,
  LoadingOverlay,
  useBodyScrollLock,
  useEscapeKey,
} from "./components";

export type {
  ButtonProps,
  ButtonVariant,
  ButtonSize,
  CardProps,
  CardVariant,
  CardPadding,
  InputProps,
  TextareaProps,
  SelectProps,
  SelectOption,
  BadgeProps,
  BadgeVariant,
  BadgeSize,
  AvatarProps,
  AvatarSize,
  DividerProps,
  DividerOrientation,
  SkeletonProps,
  SkeletonVariant,
  SpinnerProps,
  SpinnerSize,
  SidebarProps,
  SidebarItemProps,
  TopHeaderProps,
  SearchBarProps,
  NotificationMenuProps,
  NotificationMenuItem,
  ProfileMenuProps,
  ProfileMenuItem,
  BreadcrumbProps,
  BreadcrumbItem,
  HeroBannerProps,
  StatCardProps,
  AnnouncementCardProps,
  ActivityCardProps,
  TaskCardProps,
  EventCardProps,
  QuickActionCardProps,
  ProfileCardProps,
  ProfileCardField,
  DataStatusProps,
  EmptyStateProps,
  DataTableProps,
  DataTableColumn,
  TimelineProps,
  TimelineItem,
  CalendarCardProps,
  CalendarCardDay,
  ChartContainerProps,
  MetricCardProps,
  AlertProps,
  AlertTone,
  ToastProps,
  ToastTone,
  ToastViewportProps,
  ModalProps,
  ModalSize,
  ConfirmationDialogProps,
  DrawerProps,
  DrawerSide,
  DrawerSize,
  LoadingOverlayProps,
} from "./components";
